"""Application-level defaults and tunable constants."""

from __future__ import annotations

from pathlib import Path

from geo_map_exp_extractor.pricing import (
    DEFAULT_MODEL,
    DEFAULT_SERVICE_TIER as CATALOG_DEFAULT_SERVICE_TIER,
    SUPPORTED_MODELS as CATALOG_SUPPORTED_MODELS,
    SUPPORTED_REASONING_EFFORTS as CATALOG_SUPPORTED_REASONING_EFFORTS,
    SUPPORTED_SERVICE_TIERS as CATALOG_SUPPORTED_SERVICE_TIERS,
    get_model_options,
)

SCHEMA_VERSION = "1.0"

DEFAULT_REASONING_EFFORT = get_model_options(DEFAULT_MODEL).default_reasoning_effort
DEFAULT_SERVICE_TIER = CATALOG_DEFAULT_SERVICE_TIER
SUPPORTED_MODELS = CATALOG_SUPPORTED_MODELS
SUPPORTED_REASONING_EFFORTS = CATALOG_SUPPORTED_REASONING_EFFORTS
SUPPORTED_SERVICE_TIERS = CATALOG_SUPPORTED_SERVICE_TIERS

DEFAULT_IMAGE_DETAIL = "high"
SUPPORTED_IMAGE_DETAILS = ("high", "low", "auto")
DEFAULT_MAX_OUTPUT_TOKENS = 12000
DEFAULT_MAX_IMAGE_SIDE_PX = 2800

DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_BACKOFF_SECONDS = 1.5

DEFAULT_OUTPUT_DIR_NAME = "outputs"

# Local cache for request fingerprints and reusable extraction payloads.
REQUEST_CACHE_DIR = Path(".cache") / "geo_map_exp_extractor" / "requests"
